<?php 
	define('use_hdr', true);
	define('use_ftr', true);
?>
<div class="container dark">
	<h1>Elements</h1>
	<ul class="elements-list">
		<li><a href="/?v=elements&amp;e=navs">Navs</a></li>
		<li><a href="/?v=elements&amp;e=buttons">Buttonss</a></li>
		<li><a href="/?v=elements&amp;e=forms">Forms</a></li>
		<li><a href="/?v=elements&amp;e=landings">Landings</a></li>
		<li><a href="/?v=elements&amp;e=profiles">Profiles</a></li>
		<li><a href="/?v=elements&amp;e=galleries">Galleries</a></li>
		<li><a href="/?v=elements&amp;e=timelines">Timelines</a></li>
		<li><a href="/?v=elements&amp;e=dashboards">Dashboards</a></li>
		<li><a href="/?v=elements&amp;e=dashboards">Maps</a></li>
	</ul>
</div>