<?php 
	define('use_hdr', true);
	define('use_ftr', true);
?>

<div class="container dark">
	<h1>Navs</h1>
	<div class="row">
	<div class="col-lg-6"></div>
	<div class="col-lg-6">
	<pre><code class="language-markup">&lt;!DOCTYPE html>
&lt;html>
&lt;head>
	...
	&lt;link href="app.css" rel="stylesheet" />
	&lt;/head>
&lt;body>
	...
	&lt;script src="app.js">&lt;/script>
&lt;/body>
&lt;/html></code></pre>
	</div>
	</div>
</div>